### PR TITLE
hu locale

### PR DESCRIPTION
**Pull request by ovari**

### CODE REVIEW

**Comment by ovari** [comment]
@WC2-Foundation can you please accept this pull request? Thank you

**Comment by woeterman94** [comment]
Don't think this repo is still maintained.

**Comment by ovari** [comment]
@woeterman94 what can be done then? Thank you

**Comment by woeterman94** [comment]
I'd suggest creating a fork of the repo if this one is no longer maintained by the author. As long as the plugin name starts with ep_ it will be visible in the ether pad plugins page.

I can help you set it up if you like.

**Comment by woeterman94** [comment]
I'd suggest renaming this to ep_tables5 and publishing it to npm

https://github.com/ovari/ep_tables4

**Comment by ckliao-nccu** [comment]
@woeterman94 @ovari Are you still working any of table plugins?

**Comment by ovari** [comment]
@woeterman94 Sorry for the very late reply. Can this plugin be added to the main plugins so that we don't have it in our repo? We like to provide patches that can be merged and then delete our forks. Can this plugin be moved to `ether/` or https://www.npmjs.com/~etherpad?
https://github.com/ether/etherpad-lite/issues/4337#issuecomment-698469021
Perhaps @rhansen @Gared @webzwo0i @translatewiki @orblivion can help?
https://github.com/ether/etherpad-lite/issues/4337#issuecomment-698879066

@ckliao-nccu Happy for you to work on this plugin as we have only been providing `hu` translations.

Thank you

**Comment by ckliao-nccu** [comment]
@ovari I have forked this repo to [ep_table5 ](https://github.com/ckliao-nccu/ep_tables5) and try to fix the problems [seballot/ep_tables2/issues/35](https://github.com/seballot/ep_tables2/issues/35) bring up.

So far I have fixed some of the major problem, but still a lot to fix.

**Comment by ovari** [comment]
@ckliao-nccu
1. Have you got all our `hu` translations?
2. Can we delete [ovari/ep_tables4](https://github.com/ovari/ep_tables4)?
3. If you need any more strings to be translated into `hu`, please let us know.

Thank you

**Comment by ckliao-nccu** [comment]
@ovari 

1. I did, using the last update from this pull request.
2. It's up to you. But I haven't publish [ep_table5 ](https://github.com/ckliao-nccu/ep_tables5)yet, since it still have lots of bugs.
    But you can give it a try, or check out [this ](http://exp-ctl-wiki-2020.dlll.nccu.edu.tw:3191/)web site which I'm running for development.
3.  Will do, thanks for your help in advance.

**Comment by woeterman94** [comment]
I'm sorry I've been very busy lately. If you want to move this to `ether/ maybe` @JohnMcLear can help you out.

**Comment by ovari** [comment]
Closing pull request as `hu` added to [ep_table5](https://github.com/ckliao-nccu/ep_tables5).

**Comment by ovari** [comment]
@ckliao-nccu can you move your [ep_table5](https://github.com/ckliao-nccu/ep_tables5) to `ether/`? That should make it easier for translators to discover and translate. What do you think? Thank you

**Comment by JohnMcLear** [comment]
I don't want table support in ether.  It's a nightmare to maintain and without an active maintainer I don't want that responsibility.

**Comment by JohnMcLear** [comment]
Btw if we're going to have a clear project lead, it can land in ether/ but I don't want it to be something that is overly neglected because this plugin is awesome and needs the love and care of a good maintainer 👍

**Comment by ckliao-nccu** [comment]
Yes, it's a nightmare. And I don't have enough time or skill to keep maintaining it.
But I'm willing to publish my works to npm.

**Pull request closed without merging**
